protocol: "xtls"
xtls:
 private-key: "..."
 short-id: "..."

protocol: "hysteria"
hysteria:
  auth-key: "..."
  auth-password: "..."

protocol: "xhttp"
xhttp:
  auth-key: "..."
  path: "/api/umbrella/data"

port: "443"
dest: "...:443"

protocol: "torrent"
port: "50000-50100"
torrent:
 auth-key: "..."
 info-hash: "..."
